### ISSUE TITLE
is this still active and works ?

### ISSUE THREAD

**Issue by ghost** [coinables/sweepkey#4]
i just wanted to send some bitcoins programatically using only private key. 
so i would like to know, does this works ?

thanks

**Comment by coinables** [comment]
Are you asking if the website works, sweepkey.org -- or are you asking if the nodejs code from this repo is still up-to-date? Answers to both are yes.   I did have the website down for maintenance for about 5 minutes just a little bit ago.

**Comment by ghost** [comment]
i was asking if the nodejs code from this repo is still up-to-date., 
thanks for the quick reply.

**Comment by coinables** [comment]
No problem, thanks. By the way the default fee in the app.js is only 20 satoshis per byte. That would be the only thing that is out-dated. Line 144 of app.js if you want to change it.

**Comment by ghost** [comment]
what do you suggest i set the avg. fee per byte , so the transaction gets confirmed as soon as possible. 
thanks

**Comment by coinables** [comment]
It fluctuates regularly. I've tried using [21.co bitcoin fees estimator API](https://bitcoinfees.21.co/api/v1/fees/recommended) but it seems to always recommend way more than necessary.  So I've been using 50% of what their API recommends and that's been working well so far.

**Comment by ghost** [comment]
i have set it to default 20 for now, will do test transaction will see, how long it takes., to process.

can i use curl to do post data to /address 

will it work ? or does it needs to be loaded in browser. i am trying to programatically send bitcoins.

**Comment by coinables** [comment]
Yes you can send a post request to the `/address` endpoint just needs to have two post data params `pkey` and `addy` where pkey is the private key you are sweeping funds from, and addy being the address to receive the funds. Just make sure the private key you provide has a sufficient balance to send after covering mining fees (at least 0.0003 should be enough).

**Comment by ghost** [comment]
is there way, you could add a feature so that, it will calculate the fee by itself and if the amount is not sufficient, it will lower the fees until transaction gets processed.
thanks.

**Comment by coinables** [comment]
Been meaning to do that, already had most of it finished. Done and commited to master. https://github.com/coinables/sweepkey/commit/260abb5f2d50d98f69bdc0317dc3b881b912f3c9

**Comment by ghost** [comment]
do i have to do "post request to the /address endpoint," or can i pass "private_key and btc address directly in app.js" . i mean is it necessary to run it on webserver ? or i can do it internally using custom functions created by you.
i am trying to speed up the process, by lowering curl requests .
thanks

**Comment by coinables** [comment]
A webserver is not necessary. You can run nodejs scripts locally just a script, similar to how you would with python. Yes you can tweak it to load in N number of private keys into an array and then do a foreach loop that will pump each key through a sweep function, similar to the address endpoint but just make it a function that takes a private key as a parameter. What are you doing exactly that requires so much sweeping?

**Comment by ghost** [comment]
i am working on web service, which lets users sweep coins ASAP to their backup wallets. In case some funds are spent from their wallet.
Thanks.
