### ISSUE TITLE
Why are we not using blockchain.info API instead of chain.so and blockcypher.com

### ISSUE THREAD

**Issue by ghost** [coinables/sweepkey#7]
hi, i was wondering why are we not using blockchain.info API calls instead of 
https://chain.so/api/v2/get_tx_unspent/btc/"+address
to get UTXO
and 
https://api.blockcypher.com/v1/btc/main/txs/push
to push TX
?
Is there any specific reason.
Thanks

**Comment by coinables** [comment]
In order to distribute the processes and requests to prevent API limit throttling. Hit 3 sites once per request, instead of hitting one site 3 times. Allows for 3x amount of usage with these API providers.
