### ISSUE TITLE
Why is txSize is always 44 + 180 * bestHourFee ?

### ISSUE THREAD

**Issue by ghost** [coinables/sweepkey#9]
i mean isn't it like fixed for all transactions happening while bestHourFee is same.

so basically if bestHourFee  = 100

then fee will be 
(44 + 180) * 100 = 22400 satoshis ? for all transactions.

i thought fees do vary , depending on the transaction size.

line 126 , 142 , 145

thanks.,

**Comment by coinables** [comment]
Its not foxed. It's within a loop based on number of inputs. 
180 per input, 
Since its a sweep there's only 1 output , 40 bytes, then 4 more for version bytes.
